Feature/substitution live page
xxlo-devs/eru pull request #104
Opened 2020-09-12 14:18 UTC by KanarekLife

fixes #92

2020-09-12 23:22 UTC, Bazik33 requested changes
(1) There is a bug in UploadSubstitutionsCommandHandler: a class that IS NOT in DbContext BUT has been just added (so it's in newClasses List) will never be added to trackedClasses. Thus, lines from 32 to 52 should look like this: 
```csharp
foreach (var @class in classes)
{
    var tmpClass = await _context.Classes.FirstOrDefaultAsync(x => x.Year == @class.Year && x.Section == @class.Section, cancellationToken);
    if (tmpClass == null && !newClasses.Any(x=>x.Year == @class.Year && x.Section == @class.Section))
    {
        var entity = await _context.Classes.AddAsync(@class, cancellationToken);
        newClasses.Add(entity.Entity);
        trackedClasses.Add(entity.Entity);   
    }
    else
    {
        trackedClasses.Add(tmpClass);
    }
}
```

(2) You can consider deleteing some migrations you've created. This will help keep the project clean.

2020-09-12 23:22 UTC, Bazik33 commented on tests/eru.Application.Tests/FakeDbContext.cs
> +            });
Does not match with real 'ApplicationDbContext.cs'

2020-09-12 23:22 UTC, Bazik33 commented on src/eru.WebApp/Pages/Substitutions.cshtml
> +    </div>
```suggestion
    <h1 class="title">@Localizer["title"]</h1>
    @if (Model.SubstitutionsRecord == null)
    {
    <h3 class="subtitle">@Localizer["content-unavailable"]</h3>
    }
    else
    {
    <h3 class="subtitle">@Localizer["uploaded-on"] @Model.SubstitutionsRecord.UploadDateTime.ToShortDateString()</h3>
    <h3 class="subtitle">@Localizer["for-date"] @Model.SubstitutionsRecord.SubstitutionsDate.ToShortDateString()</h3>
    <div class="table-container">
        <table class="table is-bordered is-striped is-fullwidth">
                <thead>
                <tr>
                    <th>@Localizer["lesson"]</th>
                    <th>@Localizer["classes"]</th>
                    <th>@Localizer["subject"]</th>
                    <th>@Localizer["teacher"]</th>
                    <th>@Localizer["groups"]</th>
                    <th>@Localizer["room"]</th>
                    <th>@Localizer["details"]</th>
                    <th>@Localizer["note"]</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var substitution in Model.SubstitutionsRecord.Substitutions)
                {
                    <tr>
                        <td>@substitution.Lesson</td>
                        <td>@string.Join(';',substitution.Classes)</td>
                        <td>@substitution.Subject</td>
                        <td>@substitution.Teacher</td>
                        <td>@substitution.Groups</td>
                        <td>@substitution.Room</td>
                        @if (substitution.Cancelled)
                        {
                            <td>@Localizer["canceled"]</td>
                        }
                        else
                        {
                            <td>@substitution.Substituting</td>
                        }
                        <td>@substitution.Note</td>
                    </tr>
                }
                </tbody>
            </table>
    </div>
    }
```

When there are no substitutions in database application throws an [exception](https://imgur.com/a/7Dd5w2Y).

2020-09-13 08:04 UTC, KanarekLife commented
Without Id on Substitution and auto generation of Id in FakeDbContext tests couldn't be runned so I had to fix it.

2020-09-13 09:45 UTC, KanarekLife commented
Okey I managed to fix it ;)

2020-09-13 12:05 UTC, Bazik33 approved these changes

2020-09-13 12:05 UTC, Bazik33 commented on src/eru.WebApp/appsettings.json
> +    "ConnectionString": "Host=localhost;Username=eru;Password=Minecraft5066!;Database=eru"
```suggestion
    "ConnectionString": "Host=myserver;Username=mylogin;Password=mypass;Database=mydatabase;"
```

2020-09-13 12:12 UTC, merged